export interface SilenceGap {
  start: number; // in seconds
  end: number;
  duration: number;
}

export interface SilenceDetectionOptions {
  thresholdDb?: number; // e.g. -35 dB
  minDurationSec?: number; // minimum silence length to flag, e.g. 0.4s
  paddingSec?: number; // buffer to preserve around speech, e.g. 0.08s
}

export interface SubtitleSegment {
  start: number; // seconds
  end: number;
  text: string;
}

/**
 * Real audio sample-based silence detection using Root Mean Square (RMS) energy windows.
 * Directly analyzes decoded PCM audio channel data.
 */
export function analyzeAudioBufferForSilences(
  audioBuffer: AudioBuffer,
  options: SilenceDetectionOptions = {}
): SilenceGap[] {
  const thresholdDb = options.thresholdDb ?? -35;
  const minDurationSec = options.minDurationSec ?? 0.4;
  const paddingSec = options.paddingSec ?? 0.08;

  const sampleRate = audioBuffer.sampleRate;
  const channelData = audioBuffer.getChannelData(0); // primary channel
  const totalSamples = channelData.length;

  // Window size: 40ms
  const windowSize = Math.floor(sampleRate * 0.04);
  const totalWindows = Math.floor(totalSamples / windowSize);

  // Compute linear amplitude threshold from dB: 10^(dB / 20)
  const linearThreshold = Math.pow(10, thresholdDb / 20);

  const silentWindows: boolean[] = new Array(totalWindows).fill(false);

  for (let w = 0; w < totalWindows; w++) {
    const offset = w * windowSize;
    let sumSquares = 0;
    for (let i = 0; i < windowSize; i++) {
      const val = channelData[offset + i];
      sumSquares += val * val;
    }
    const rms = Math.sqrt(sumSquares / windowSize);
    if (rms < linearThreshold) {
      silentWindows[w] = true;
    }
  }

  // Group continuous silent windows into intervals
  const gaps: SilenceGap[] = [];
  let inSilence = false;
  let silenceStartWindow = 0;

  for (let w = 0; w < totalWindows; w++) {
    if (silentWindows[w] && !inSilence) {
      inSilence = true;
      silenceStartWindow = w;
    } else if (!silentWindows[w] && inSilence) {
      inSilence = false;
      const startSec = (silenceStartWindow * windowSize) / sampleRate;
      const endSec = (w * windowSize) / sampleRate;
      const rawDur = endSec - startSec;

      if (rawDur >= minDurationSec) {
        // Apply safety padding around speech
        const safeStart = Number((startSec + paddingSec).toFixed(3));
        const safeEnd = Number((Math.max(safeStart, endSec - paddingSec)).toFixed(3));
        const finalDur = Number((safeEnd - safeStart).toFixed(3));

        if (finalDur >= 0.2) {
          gaps.push({ start: safeStart, end: safeEnd, duration: finalDur });
        }
      }
    }
  }

  // Handle trailing silence
  if (inSilence) {
    const startSec = (silenceStartWindow * windowSize) / sampleRate;
    const endSec = (totalWindows * windowSize) / sampleRate;
    const rawDur = endSec - startSec;
    if (rawDur >= minDurationSec) {
      const safeStart = Number((startSec + paddingSec).toFixed(3));
      const safeEnd = Number(endSec.toFixed(3));
      const finalDur = Number((safeEnd - safeStart).toFixed(3));
      if (finalDur >= 0.2) {
        gaps.push({ start: safeStart, end: safeEnd, duration: finalDur });
      }
    }
  }

  return gaps;
}

/**
 * Converts timestamp in seconds to standard SRT format (hh:mm:ss,ms)
 */
function formatSrtTime(sec: number): string {
  const s = Math.max(0, sec);
  const hrs = Math.floor(s / 3600);
  const mins = Math.floor((s % 3600) / 60);
  const secs = Math.floor(s % 60);
  const ms = Math.floor((s % 1) * 1000);

  const pad = (n: number, z = 2) => n.toString().padStart(z, '0');
  return `${pad(hrs)}:${pad(mins)}:${pad(secs)},${pad(ms, 3)}`;
}

/**
 * Converts timestamp in seconds to standard WebVTT format (hh:mm:ss.ms)
 */
function formatVttTime(sec: number): string {
  const s = Math.max(0, sec);
  const hrs = Math.floor(s / 3600);
  const mins = Math.floor((s % 3600) / 60);
  const secs = Math.floor(s % 60);
  const ms = Math.floor((s % 1) * 1000);

  const pad = (n: number, z = 2) => n.toString().padStart(z, '0');
  return `${pad(hrs)}:${pad(mins)}:${pad(secs)}.${pad(ms, 3)}`;
}

/**
 * Generates SubRip (.srt) subtitle text from segments
 */
export function exportToSRT(segments: SubtitleSegment[]): string {
  return segments
    .map((seg, i) => {
      return `${i + 1}\n${formatSrtTime(seg.start)} --> ${formatSrtTime(seg.end)}\n${seg.text}\n`;
    })
    .join('\n');
}

/**
 * Generates WebVTT (.vtt) subtitle text from segments
 */
export function exportToVTT(segments: SubtitleSegment[]): string {
  const header = 'WEBVTT - Generated by NOVA Studio AI\n\n';
  const body = segments
    .map((seg, i) => {
      return `${i + 1}\n${formatVttTime(seg.start)} --> ${formatVttTime(seg.end)}\n${seg.text}\n`;
    })
    .join('\n');
  return header + body;
}

/**
 * Parses SRT or VTT text back into timestamped subtitle segments
 */
export function parseSRTorVTT(text: string): SubtitleSegment[] {
  const lines = text.replace(/\r\n/g, '\n').split('\n');
  const segments: SubtitleSegment[] = [];

  let currentStart = 0;
  let currentEnd = 0;
  let currentText = '';

  const timeRegex = /(?:(\d+):)?(\d{2}):(\d{2})[,.](\d{3})\s*-->\s*(?:(\d+):)?(\d{2}):(\d{2})[,.](\d{3})/;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line || line === 'WEBVTT') continue;

    const match = line.match(timeRegex);
    if (match) {
      if (currentText) {
        segments.push({ start: currentStart, end: currentEnd, text: currentText.trim() });
        currentText = '';
      }

      const h1 = match[1] ? parseInt(match[1]) : 0;
      const m1 = parseInt(match[2]);
      const s1 = parseInt(match[3]);
      const ms1 = parseInt(match[4]);
      currentStart = h1 * 3600 + m1 * 60 + s1 + ms1 / 1000;

      const h2 = match[5] ? parseInt(match[5]) : 0;
      const m2 = parseInt(match[6]);
      const s2 = parseInt(match[7]);
      const ms2 = parseInt(match[8]);
      currentEnd = h2 * 3600 + m2 * 60 + s2 + ms2 / 1000;
    } else if (!/^\d+$/.test(line) && currentStart !== currentEnd) {
      currentText += (currentText ? ' ' : '') + line;
    }
  }

  if (currentText) {
    segments.push({ start: currentStart, end: currentEnd, text: currentText.trim() });
  }

  return segments;
}
